which: no nvcc in (/cvmfs/sft.cern.ch/lcg/releases/cuda/12.4-4899e/x86_64-el9-gcc11-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/LCG_106_cuda/cuda/12.4/x86_64-el9-gcc11-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-de683/x86_64-el9/bin:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/bin:/nfs/dust/cms/user/puschman/rivet/bin:/nfs/dust/cms/user/puschman/rivet/lib64/../bin:/nfs/dust/cms/user/puschman/tf_venv/bin:/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.32.02/x86_64-almalinux9.4-gcc114-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/LCG_106_cuda/CMake/3.26.2/x86_64-el9-gcc11-opt/bin:/cvmfs/sft.cern.ch/lcg/releases/gcc/11.3.0-de683/x86_64-el9/bin:/cvmfs/sft.cern.ch/lcg/releases/binutils/2.40-acaab/x86_64-el9/bin:/usr/share/Modules/bin:/afs/desy.de/common/passwd:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin)
Traceback (most recent call last):
  File "/nfs/dust/cms/user/puschman/DCTR_Paper/DCTR_FP/20240820_MSE_vs_BCE/./submit_DCTR_training_NNLO_MSE_vs_BCE.py", line 106, in <module>
    x1_rwgt_mse = np.load(f'{save_path}{mse_label}_X1_rwgt.npy')
  File "/nfs/dust/cms/user/puschman/tf_venv/lib/python3.9/site-packages/numpy/lib/npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './saved_models/DCTR_NNLO_mse_pos_rwgt_2_batchsize_32768_X1_rwgt.npy'
